name: Build
on:
  push:
    branches-ignore:
      - main

permissions:
  contents: write 
  actions: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "ğŸŒ Fetching code"
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
        with:
          persist-credentials: false
      - name: "ğŸŒ Logging in to Docker Registry"
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # tag=v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "ğŸš§ Building image"
        run: docker build -t ghcr.io/thepwagner-org/debian-bullseye:${{github.sha}} .

      - name: "ğŸ•µï¸ Setup Syft"
        uses: anchore/sbom-action/download-syft@ce4a7cf05d7b684693d7b6bba97bfbee56806edb # v0.7.0
      - name: "ğŸ•µï¸ Generate SBOM"
        run: syft packages -o spdx-json=sbom.spdx.json ghcr.io/thepwagner-org/debian-bullseye:${{github.sha}}
      - name: "ğŸ•µï¸ Upload SBOM"
        uses: actions/upload-artifact@v3
        with:
          name: spdx-json
          path: sbom.spdx.json

      - name: "ğŸ‘® Verify SBOM"
        run: |
          # Exit if packages match the committed SBOM
          BUILT_PACKAGES=$(jq -c .packages sbom.spdx.json | sha512sum)
          STORED_PACKAGES=$(jq -c .packages Dockerfile.spdx.json | sha512sum)
          [ "${BUILT_PACKAGES}" = "${STORED_PACKAGES}" ] && exit 0

          # On mismatch, commit and push an update:
          mv sbom.spdx.json Dockerfile.spdx.json
          git config user.name "wa thepwagner"
          git config user.email "70587923+wapwagner@users.noreply.github.com"
          git add Dockerfile.spdx.json
          git commit -m'generated SBOM'
          git push "https://wapwagner:${{ secrets.WAPWAGNER_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          exit 1
